---
title: "BリーグとNBAでは得点・アシスト・リバウンドの相関は異なるか？"
author: "rnsr0371"
date: "7/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
こんにちは、らんそうるいです。またまたまたまた偏相関係数を使ってみるシリーズです。[偏相関係数を使って出場時間の影響を取り除いたスタッツ同士の関係を調べる](https://rnsr0371.boy.jp/2021/07/23/partial_correlation/)という記事で、Bリーグで一部のスタッツの偏相関係数を算出してみました。この記事に寄せられた反応の中で、とても興味深いものがあったので、それを検討してみるというのが今回の記事の目標です。

興味深い反応というのは、[しんたろう](https://twitter.com/MaMakin007)様からいただいた次のような内容です。すなわち「(Bリーグでは)外国籍選手の得点が多いので(得点と)アシストの相関が弱」い「NBAだと全然違うんだろうなー」というものです。

確かにBリーグはNBAと比べて得点源の選手が外国籍選手でかつインサイドの選手に集中しているという特徴があると思います。すると、仮説として次のようなものが浮かびました。

- 仮説1：Bリーグと比べてNBAでは、得点源の選手のポジションがバラけているので、得点とリバウンドの相関は弱いだろう。
- 仮説2：Bリーグと比べてNBAでは、得点源の選手のポジションがバラけているので、得点とアシストの相関は正の方向に強いだろう。

これらの仮説を調べるために、出場時間の影響を取り除いた偏相関係数と、時間あたりのスタッツの単純相関係数を算出し、BリーグとNBAで比較を行います。ただ、技術力不足で「得点源の選手のポジションがバラけているので」というプロセスに関する部分は検討できませんでした。それでは行ってみましょう。

## データの準備
### Bリーグ
生データとしてrintaromasuda様の[github](https://github.com/rintaromasuda/bleaguer/tree/master/inst/extdata)から、teams.csvとgames_boxscore_202021.csvを使用させていただきました。これらのデータを加工して、B1 2020-21シーズンの各選手の平均スタッツを作成しました。

### NBA
生データとして[NBAsuffer](https://www.nbastuffer.com/2020-2021-nba-player-stats/)から、2020-21レギュラーシーズンのデータを使用しました。今回の分析で必要な
選手名・出場時間・得点・リバウンド・アシスト・ターンオーバーを抽出し、データセットとしました。

## 分析
### 単純相関係数の確認
以下のコードを実行し、相関行列を作成しました。まず、Bリーグから。

```{R}
#必要なライブラリのインポート
library(tidyverse)
library(ppcor)
library(corrplot)

#データのインポート
bleague=read_csv("data/bleague_stats_202021.csv")
nba=read_csv("data/nba_stats202021.csv")

#bleagueから必要な列だけ選択する
bleague=bleague %>% dplyr::select(Player,MIN,PTS,TR,AS,TO)

#相関行列の確認
#Bリーグ202021シーズンの相関行列
bleague %>% dplyr::select(-Player) %>% cor(.) %>% corrplot.mixed(.)
```

続いてNBAです。
```{R}
#NBA202021(レギュラーシーズン)の相関行列
nba %>% dplyr::select(-Player) %>% cor(.) %>% corrplot.mixed(.)
```

2つの相関行列を比較すると、すでに仮説1,2に沿ったパターンが得られています。すなわち、単純相関係数をBリーグとNBAで比較すると、得点とリバウンドの相関係数はBリーグの方が高く、得点とアシストの相関係数はNBAの方が高い、というものです。そして、やはり、出場時間が全てのスタッツを正の相関関係を持つことが分かりました。次節では、この出場時間の影響を取り除いた分析として、出場時間をパーシャルアウトした偏相関係数を使った分析と、出場時間あたりの単純相関係数を使った分析をご報告します。

### 出場時間をパーシャルアウトした偏相関係数
以下のコードを実行して、Bリーグでの偏相関係数を求めました。

```{R}
#出場時間をパーシャルアウトした偏相関係数の算出
#Bリーグから
#得点とリバウンド
bleague %>% dplyr::select(MIN,PTS,TR) %>% pcor(.) %>% .$estimate#0.554
#得点とアシスト
bleague %>% dplyr::select(MIN,PTS,AS) %>% pcor(.) %>% .$estimate#-0.247
#得点とターンオーバー
bleague %>% dplyr::select(MIN,PTS,TO) %>% pcor(.) %>% .$estimate#0.339
#リバウンドとアシスト
bleague %>% dplyr::select(MIN,TR,AS) %>% pcor(.) %>% .$estimate#-0.283
#リバウンドとターンオーバー
bleague %>% dplyr::select(MIN,TR,TO) %>% pcor(.) %>% .$estimate#0.184
#アシストとターンオーバー
bleague %>% dplyr::select(MIN,AS,TO) %>% pcor(.) %>% .$estimate#0.554
```

続いてNBAです。

```{R}
#続いてNBA
#得点とリバウンド
nba %>% dplyr::select(MIN,PTS,TR) %>% pcor(.) %>% .$estimate#0.092
#得点とアシスト
nba %>% dplyr::select(MIN,PTS,AS) %>% pcor(.) %>% .$estimate#0.338
#得点とターンオーバー
nba %>% dplyr::select(MIN,PTS,TO) %>% pcor(.) %>% .$estimate#0.487
#リバウンドとアシスト
nba %>% dplyr::select(MIN,TR,AS) %>% pcor(.) %>% .$estimate#-0.159
#リバウンドとターンオーバー
nba %>% dplyr::select(MIN,TR,TO) %>% pcor(.) %>% .$estimate#0.114
#アシストとターンオーバー
nba %>% dplyr::select(MIN,AS,TO) %>% pcor(.) %>% .$estimate#0.626
```

結果をまとめます。

- Bリーグでは得点とリバウンドの偏相関係数が0.554あるのに対し、NBAでは0.092しかない。

  - 「仮説1：Bリーグと比べてNBAでは、得点源の選手のポジションがバラけているので、得点とリバウンドの相関は弱いだろう」を支持する結果です。

- Bリーグでは得点とアシストの偏相関係数が-0.247であるのに対し、NBAでは0.338である。つまり、相関関係が逆転している。

  - 「仮説2：Bリーグと比べてNBAでは、得点源の選手のポジションがバラけているので、得点とアシストの相関は正の方向に強いだろう」を支持する結果です。
  
ただし、注意点があります。それは「得点源の選手のポジションがバラけているので」という結果に対する説明の部分です。今回は偏相関係数の値を比べているだけなので、この部分については検討できていません。この説明を検討するアイディアが浮かばなかったので、今後の課題と言えます。

### 時間あたりのスタッツを使った単純相関係数
この分析は補足的な分析です。この分析方法と偏相関係数を使った分析の違いや使うべき状況の違いが、私には分からないので、掲載しました。結果としては前節とパラレルなものです。

まずはデータの加工から。

```{R}
#時間あたりの得点、リバウンド、アシスト、ターンオーバーの単純相関を調べる。
#時間あたりのスタッツを計算してデータセットに加える
bleague=bleague %>% mutate(PTS_per_MIN=PTS/MIN,
                   TR_per_MIN=TR/MIN,
                   AS_per_MIN=AS/MIN,
                   TO_per_MIN=TO/MIN)

nba=nba %>% mutate(PTS_per_MIN=PTS/MIN,
                           TR_per_MIN=TR/MIN,
                           AS_per_MIN=AS/MIN,
                           TO_per_MIN=TO/MIN)
```

続いて、Bリーグでのデータを示します。

```{R}
#相関行列を描く
#Bリーグから
cor_bleague=bleague %>% dplyr::select(PTS_per_MIN,TR_per_MIN,AS_per_MIN,TO_per_MIN) %>% cor(.,use="pairwise.complete.obs")
cor_bleague
corrplot.mixed(cor_bleague)
```

最後にNBAです。

```{R}
#続いてNBA
cor_nba=nba %>% dplyr::select(PTS_per_MIN,TR_per_MIN,AS_per_MIN,TO_per_MIN) %>% cor(.,use="pairwise.complete.obs")
cor_nba
corrplot.mixed(cor_nba)
```

結果をまとめます。

- Bリーグでは時間あたりの得点とリバウンドの相関係数が0.482あるのに対し、NBAでは0.107しかない。

  - 「仮説1：Bリーグと比べてNBAでは、得点源の選手のポジションがバラけているので、得点とリバウンドの相関は弱いだろう」を支持する結果です。

- Bリーグでは時間あたりの得点とアシストの相関係数が0.103であるのに対し、NBAでは0.312ある。

  - 「仮説2：Bリーグと比べてNBAでは、得点源の選手のポジションがバラけているので、得点とアシストの相関は正の方向に強いだろう」を支持する結果です。

結果の解釈の注意点は偏相関係数を使った分析と同じなので省略します。

## 終わりに
この記事では、Twitterでいただいた興味深い反応――BリーグとNBAでは傾向が異なるのではないか、を検討してみました。その結果、BリーグとNBAを比較すると、得点とリバウンドの相関関係はBリーグの方が強く、得点とアシストの相関関係は逆転していてBリーグではほとんど関係がないか負の相関、NBAでは正の相関が見られるということが分かりました。この結果は、おそらくBリーグでは得点源の選手がインサイドの外国籍選手に集中しているということに起因するのだと考えられます。

最後に興味深い反応と仮説をくださった[しんたろう](https://twitter.com/MaMakin007)様に感謝してこの記事を終わりたいと思います。ありがとうございました。
